### ISSUE TITLE
invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"

### ISSUE THREAD

**Issue by priyanko83** [dotnet-architecture/eShopOnContainers#1261]
I am running deployAll.ps1 with the required parameters.
All helm infrastructure and charts are installing fine except Gateway Charts: apigwws & apigwms where I am getting below error logs.

Could you kindly investigate what's wrong and update the fixed files? I am very much interested in this sample application and would really like to get it running in my dev cluster.

Thanks in advance for your support!

### **Installing Api Gateway Chart: apigwms**
Helm Command: helm install eshop-apigwms -f app.yaml -f inf.yaml -f ingress_values.yaml  --set app.name=eshop --set inf.k8s.dns=eshop.2d318db21eda4f209268.centralus.aksapp.io  --set image.pullPolicy=Always --set inf.mesh.enabled=False --set ingress.hosts={eshop.2d318db21eda4f209268.centralus.aksapp.io} --set inf.tls.enabled=False apigwms
**_Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ConfigMap.data.admin): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string", ValidationError(ConfigMap.data.static_resources): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"]_**

### **Installing Api Gateway Chart: apigwws**
Helm Command: helm install eshop-apigwws -f app.yaml -f inf.yaml -f ingress_values.yaml  --set app.name=eshop --set inf.k8s.dns=eshop.2d318db21eda4f209268.centralus.aksapp.io  --set image.pullPolicy=Always --set inf.mesh.enabled=False --set ingress.hosts={eshop.2d318db21eda4f209268.centralus.aksapp.io} --set inf.tls.enabled=False apigwws
**_Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ConfigMap.data.admin): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string", ValidationError(ConfigMap.data.static_resources): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"]_**

**Comment by priyanko83** [comment]
@mvelosop @erikpique -

I am really looking forward to this excellent sample app you guys have built as a starting point for coming up with AKS based deployment/devops model to propose to my clients. 

Hence,  it would be very helpful for me if you could help me out with the issue I'm facing.

Many thanks in advance for your help on this.

**Comment by hpr112** [comment]
I get the same error when trying to deploy with azure devops release, but it works fine when deploying with deploy-all.ps1...

**Comment by olaplassen** [comment]
I am experiencing the same error when using Azure Devops realese pipeline.

**Comment by priyanko83** [comment]
I am getting it even when I run using deploy-all.ps1
All helm infrastructure and charts are installing fine except the two charts mentioned in issue description

**Comment by bjorntli** [comment]
Pls send halp.

**Comment by hpr112** [comment]
Seems to be an error with the syntax in envoy.yaml and the understanding of indent. The fix for me was to mark all the code in envoy.yaml files and add one indent.

**Comment by priyanko83** [comment]
@hpr112  @mvelosop - Isn't this a pain to manually do such indentation and figure out what's wrong? Are you aware of any IDE/Tooling that can autodetect/show intellisense such that we dont have to spend hour in idnetifying/correcting indentation manually? 

I find it immensely painful to create those long running deployment.yaml files, use if/else/loops to replace values from values.yaml files

**Comment by sughosneo** [comment]
Hi @priyanko83, you could use some tool like [Yamllint](http://www.yamllint.com/) to validate and format your YAML(s). 

Also, just to let you know we have recently updated our scripts to support latest version of K8s in both local and aks related deployment. If you want you could give it a try and see if that's helpful. 

Here are the links for the wiki pages. 

[Local K8s](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)
[AKS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))

Thank you.

**Comment by sughosneo** [comment]
Hi @priyanko83 , I am closing this issue as of now. If you face any challenges please feel free to write back and reopen it. 

Thank you.

**Comment by mgsf** [comment]
@sughosneo I tried deploying to AKS (.\deploy-all-mac.ps1) and still get the above error. Tried to validate the envoy.yaml at Yamllint as mentioned above and it is shown as Valid. Then indented as suggested by @hpr112 but still this error occurs. Some help in this regard is highly appreciated.

**Comment by mgsf** [comment]
Try the [link ](https://gayanf.medium.com/deploy-eshoponcontainers-to-aks-357ac48cda60)on how to overcome this issue and get the deployment done

**Comment by sughosneo** [comment]
> I have written how to overcome this issue. Try the [link ](https://gayanf.medium.com/deploy-eshoponcontainers-to-aks-357ac48cda60) and get the deployment done

Hi @mgsf , thank you for the update and feedback. I will test out the AKS deployment scenario again from the macOS environment to see if there is any further issue `envoy.yaml`. Will update this issue accordingly.

**Comment by Rosenberg96** [comment]
I am experiencing this exact issue on Mac with a local Kubernetes Cluster. The steps outline by @mgsf did unfortunately not resolve my issues.

**Comment by squasta** [comment]
I got the same issue trying to deploy eShoponContainers to a brand new AKS. I tried the solution proposed by @mgsf but got the same error message... that is frustrating because I already made this sample work last year, now it is becoming fat with bugs at installation :(

**Comment by sughosneo** [comment]
Reopening this issue as it needs further investigation.

**Comment by Rosenberg96** [comment]
@squasta, @sughosneo I fixed this with a very minor change to the `envoy-cm.yml` in the `apigwms` and `apigwws` helm template. Here, the `apigwms`, but removing the indent in the final line of `apigwws`'s `envoy-cm.yml` file should do the trick. 

```
{{- $name := include "apigwws.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "envoy-{{ $name }}"
  labels:
    app: {{ template "apigwws.name" . }}
    chart: {{ template "apigwws.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "envoy.yaml").AsConfig  | indent 2 }}  <--- The indent is removed.
```
I hope this solves your issue

**Comment by sughosneo** [comment]
Hey everyone, I have done some more testing of the helm manifest files again from both Windows OS and macOS. From Windows OS there is no issue, all manifest gets deployed properly. But from macOS, I see the same issue `invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"`

When I tried the solution suggested by @mgsf and @hpr112, actually didn't resolve the problem. But when I followed the changes suggested by @Rosenberg96, actually that solved the issue. And this could be because of similar syntax followed for this *ConfigMap* `.Files.Glob` specific example in [ConfigMap and Secrets utility functions](https://helm.sh/docs/chart_template_guide/accessing_files/#configmap-and-secrets-utility-functions)

@Rosenberg96 - would you like to submit a PR ? You may want to change indentation for all 4 of the `envoy-cm.yaml` files. Will perform one more round of detailed test and then merge the changes. 

Thanks.

**Comment by sughosneo** [comment]
@squasta - Could you please try the above changes and see if it helps ? Thanks.

**Comment by excrispy** [comment]
I ran into this problem but for a different reason. My problem was I used a multi level nested map, when only a map of one level is supported.
So I had this
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: permissions
data:
  /path:
    post:
      alw: |
        admin
```

But it can only do something like this
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: permissions
data:
  /path: |
    admin
    guest
```

Maybe someone else ran into that problem. Hope that helps.

**Comment by MarinaBerthe** [comment]
Hello every one. I am writing a prometheus-configmap.yml file which is scraping two targets (prometheus and node_exporter)  , loading a rule file, and talking to
an Alertmanager


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  global:
    scrape_interval: 10s
    evaluation_interval: 10s
  rule_files:
  - rules.yml: |
      groups:
       - name: example
         rules:
         - alert: InstanceDown
           expr: up == 0
           for: 5m
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
         - 10.4.0.27:9093
    scrape_configs:
     - job_name: prometheus
       static_configs:
        - targets:
           - 10.4.0.27:9090
     - job_name: node
       static_configs:
       - targets:
          - 10.4.0.27:9100
after running this file with command " kubectl apply -f prometheus-configmap.yaml" , the returned error is: 

error: error validating "prometheus-configmap.yaml": error validating data: [ValidationError(ConfigMap.data.alerting): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string", ValidationError(ConfigMap.data.global): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string", ValidationError(ConfigMap.data.rule_files): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "array", expected "string"]; if you choose to ignore these errors, turn validation off with --validate=false


PLease, according to you, what i must do to solve this issue  ?
