### ISSUE TITLE
Error building from Windows/CLI

### ISSUE THREAD

**Issue by albertodall** [dotnet-architecture/eShopOnContainers#288]
I'm trying to build the project from CLI on Windows, 
I cloned the project, then I ran the suggested commands from CLI:

- Docker-compose -f docker-compose.ci.build.yml up
- Docker-compose up

During the "Docker-compose up" execution, I got this error message:

Building ordering.api
Step 1/6 : FROM microsoft/aspnetcore:1.1.2
 ---> 2814579b82f3
Step 2/6 : ARG source
 ---> Using cache
 ---> 2e3e57f342c1
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> ae87579d78aa
Step 4/6 : EXPOSE 80
 ---> Using cache
 ---> 3ed66b765142
Step 5/6 : COPY ${source:-obj/Docker/publish} .
ERROR: Service 'ordering.api' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder624494684/obj/Docker/publish: no such file or directory

**Comment by unaizorrilla** [comment]
Are you follow the instructions and requirements from the wiki? Dev or master branch?

**Comment by albertodall** [comment]
I followed all the instructions and requirements.
I also tried to run the scripts "build-bits.ps1" and "build-images.ps1", with no luck:

Building webspa
Step 1/6 : FROM microsoft/aspnetcore:1.1.2
 ---> 2814579b82f3
Step 2/6 : ARG source
 ---> Using cache
 ---> 3140be69bd2f
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> 1c816298faaa
Step 4/6 : EXPOSE 80
 ---> Using cache
 ---> 7161802d6c98
Step 5/6 : COPY ${source:-obj/Docker/publish} .
ERROR: Service 'webspa' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder220556062/obj/Docker/publish: no such file or directory

**Comment by unaizorrilla** [comment]
Dev branch?

**Comment by albertodall** [comment]
Yes, dev branch (sorry, I forgot to report that)

**Comment by unaizorrilla** [comment]
VS version?

**Comment by albertodall** [comment]
VS 2017 Enterprise 15.3.2

**Comment by unaizorrilla** [comment]
Is your Dev branch up to date? The team fix, yesterday,one issue related with new docker tools on 15.3.2.

You hacer more details on error, from de cli or vs?

**Comment by albertodall** [comment]
One difference I have is that I forked the project in my own GitHub repo, and I'm working on that.
I'm pretty sure the dev branches are up to date, but I'm going to double check.

**Comment by unaizorrilla** [comment]
Ok try to check If is up to date. Other people with the same issue are ok now with the latest fix committed yesterday.

Thanks

**Comment by albertodall** [comment]
Everything was up to date.
I cleaned up everything previusly built (docker images, projects...) and I build the whole project directly form Visual Studio, and it starts /http://localhost:5100). It still does not work from the command line:

Building webspa
Step 1/6 : FROM microsoft/aspnetcore:1.1.2
---> 2814579b82f3
Step 2/6 : ARG source
---> Using cache
---> 3140be69bd2f
Step 3/6 : WORKDIR /app
---> Using cache
---> 1c816298faaa
Step 4/6 : EXPOSE 80
---> Using cache
---> 7161802d6c98
Step 5/6 : COPY ${source:-obj/Docker/publish} .
ERROR: Service 'webspa' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder220556062/obj/Docker/publish: no such file or directory

**Comment by CESARDELATORRE** [comment]
@albertodall - When running "from the command line", what way do you mean?

1. Just running from Windows the following CLI commands?:
- dotnet publish solution-name.sln  (from Windows Command prompt)
- docker-compose up

2. Or do you mean building the bits from the Docker Build Container, as specified here:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)
Like running the following:
- Docker-compose -f docker-compose.ci.build.yml up
- Docker-compose up

There's probably a bug/issue in the "dotnet publish" CLI when running from within the build Container and the dotnet CLI team is currently researching it. But the error is different from what you said.

The error you are showing looks like you are trying the first way I mentioned (#1) but you didn't generate the bits first with "dotnet publish".

Can you confirm your concrete scenario?
Thanks,
Cesar.

**Comment by albertodall** [comment]
Hello Cesar,
I got the error executing:

- Docker-compose -f docker-compose.ci.build.yml up
- Docker-compose up

I didn't get any error during  the execution of the former command (Docker-compose -f docker-compose.ci.build.yml up), but I got the reported error while executing the latter (Docker-compose up).
I haven't tried the dotnet publish + docker-compose command set yet; I'll give it a try.

**Comment by OlekRia** [comment]
@albertodall Could you resolve your issue?

**Comment by albertodall** [comment]
@OlekRia Yes, with the latest version of the "dev" branch and the latest Visual Studio updates, everything seems to work.
